### PR TITLE
Upgrade to Gradle  3.1.4/4.10 and lower mininm version to API 18

### PR DESCRIPTION
**Pull request by thelittlefireman**
https://developer.android.com/reference/java/security/KeyStore AndroidKeyStore apear in API 18 not in 21

### CODE REVIEW

**Comment by leonardoxh** [comment]
Can we upgrade to gradle 4.10 ?

+ You forgot to update the `CipherStorageFactory` to return the correct implementation if the api is 18
+ Please rename the `CipherStorageApi22Test` to `CipherStorageApi18Test`
+ You forgot to upgrade the gradle wrapper to V 4.9

**Comment by thelittlefireman** [comment]
oh i haven't seen that 4.10 has been released, I changed it ;) 
"You forgot to upgrade the gradle wrapper to V 4.9" i've update the" task wrapper" and "the gradle-wrapper.properties" Have I miss something ?

Tested the sample on a S4 mini : with Android 4.4.2

**Comment by leonardoxh** [comment]
Yes, please run the command gradle wrapper and then commit the result as well.

**Comment by leonardoxh** [comment]
I also just runned here the `./gradlew connectedCheck` with the gradle 4.10 and it throws a exception... So I might think is better to keep the gradle version to `4.5.1` and just reduce the target.

**Comment by leonardoxh** [comment]
Also I tried to run the unit test with the `gradle 4.10` and I got this message: `Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.`

This eventually say the maximum supported version of gradle for android is `4.5.1` So I think we should not upgrade the gradle version yet.

**Comment by thelittlefireman** [comment]
it's a common and old known issue : https://stackoverflow.com/questions/49990933/configuration-on-demand-is-not-supported-by-the-current-version-of-the-android-g
https://developer.android.com/studio/build/optimize-your-build#configuration_on_demand

just need to uncheck this : https://prnt.sc/knt25g

**Comment by leonardoxh** [comment]
Yeah, it makes sense. Also because I need make some changes on the structure as well.

**Comment by thelittlefireman** [comment]
If you need help do not hesitate :)

**Comment by leonardoxh** [comment]
Are you going to change the remaining stuff or I can close the PR ?

**Comment by thelittlefireman** [comment]
If you think that's ok you can merge, or tell me what need to be changed :)

**Comment by leonardoxh** [comment]
I asked to you to upgrade the gradle wrapper.

The reason to have a gradle task that upgrade the wrapper is to not touch the gradle-wrapper.properties manually. So you should run the task `wrapper` to regenerate the wrapper folder etc and commit this result as well.

**Comment by thelittlefireman** [comment]
The gradle-wrapper.properties is automaticaly updated by Android Studio when you change de gradle version. If you don't change the gradle-wrapper.properties Android studio don't know where to get the dradle. the wrapper is just a downloader

**Comment by leonardoxh** [comment]
That's true in part, but that's why I have this wrapper task, so you just change the wrapper version and then `gradle wrapper` and it generates everything.

**Pull request closed without merging**
